name: CI workflow

on:
  workflow_call:
    secrets:
      FIREBASE_APP_DISTRIBUTION_KEY_BASE_64:
        required: true
      PLAY_STORE_APP_DISTRIBUTION_KEY_BASE_64:
        required: true
      KEYSTORE_BASE_64:
        required: true
      KEYSTORE_ALIAS:
        required: true
      KEYSTORE_PASSWORD:
        required: true


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set environment secrets
        env:
          FIREBASE_APP_DISTRIBUTION_KEY_STRING: ${{ secrets.FIREBASE_APP_DISTRIBUTION_KEY_BASE_64 }}
          PLAY_STORE_APP_DISTRIBUTION_KEY_STRING: ${{ secrets.PLAY_STORE_APP_DISTRIBUTION_KEY_BASE_64 }}
          KEYSTORE_STRING: ${{ secrets.KEYSTORE_BASE_64 }}
          KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        run: |
          echo "firebase_app_distribution_key_string=$FIREBASE_APP_DISTRIBUTION_KEY_STRING" >> $GITHUB_ENV
          echo "play_store_app_distribution_key_string=$PLAY_STORE_APP_DISTRIBUTION_KEY_STRING" >> $GITHUB_ENV
          echo "keystore_string=$KEYSTORE_STRING" >> $GITHUB_ENV
          echo "keystore_alias=$KEYSTORE_ALIAS" >> $GITHUB_ENV
          echo "keystore_password=$KEYSTORE_PASSWORD" >> $GITHUB_ENV

      - name: Decode keystore
        run: |
          KEYSTORE_FILE_PATH="${GITHUB_WORKSPACE}"/android/certificates
          mkdir "${KEYSTORE_FILE_PATH}"
          echo ${{ env.keystore_string }} | base64 -di > "${KEYSTORE_FILE_PATH}"/keystore.jks

      - name: Decode Firebase app distribution key
        run: |
          KEY_FILE_PATH="${GITHUB_WORKSPACE}"/android/certificates
          echo ${{ env.firebase_app_distribution_key_string }} | base64 -di > "${KEY_FILE_PATH}"/firebase-app-distribution-key.json

      - name: Decode play store key
        run: |
          KEY_FILE_PATH="${GITHUB_WORKSPACE}"/android/certificates
          echo ${{ env.play_store_app_distribution_key_string }} | base64 -di > "${KEY_FILE_PATH}"/playstore-app-distribution-key.json
          ls "${GITHUB_WORKSPACE}"/android/certificates

      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: 11

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Install dependencies to support ruby project
        working-directory: ./android
        run: |
          bundle config --global set deploy_platform_default x86_64-linux
          bundle install

      - name: Build and distribute app
        working-directory: ./android
        run: |
          export LC_ALL=en_US.UTF-8
          export LANG=en_US.UTF-8
          gradle wrapper
          bundle exec fastlane build
